pipeline {
    agent any
    stages {
        stage('Unit tests backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bug-tracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}

